export { default as Navbar } from "./Navbar/Navbar"
export { default as OurMenuCard } from "./OurMenuCard/OurMenuCard"
export { default as TestimonialsCard } from "./TestimonialsCard/TestimonialsCard"
export { default as Dot } from "./Dot/Dot"
export { default as Star } from "./Star/Star"