export { default as Banner } from "./Banner/Banner"
export { default as AboutUs } from "./AboutUs/AboutUs"
export { default as OurMenu } from "./OurMenu/OurMenu"
export { default as Testimonials } from "./Testimonials/Testimonials"
export { default as ContactUs } from "./ContactUs/ContactUs"
export { default as GroupedImages } from "./GroupedImages/GroupedImages"